### ISSUE TITLE
Integration with Webpack

### ISSUE THREAD

**Issue by nedpals** [jcbrand/pluggable.js#9]
Hi, I am creating a client-side Javascript app with the intention of making it extendable/extensible (not sure what is the proper term lol). Anyways, I was searching for a simple plug-in system that I can use (for now) in my project and I found your library. However, my app has a asset bundler (Webpack) and I know it abstracts functions as far as I know.

My question is, is the example mentioned in the readme still applies when it comes to this type of project? Is there a best practice for it when it comes to integrating pluggable with webpack? Thanks.

**Comment by jcbrand** [comment]
Hi @nedpals 

AFAIK this should still work fine with webpack. Pluggable.js is in the [UMD module format](https://github.com/umdjs/umd) which webpack can definitely load.

I'm not sure what you mean when you say that webpack's asset bundler "abstracts functions" though.

@cmrd-senya did some work using converse.js (which uses pluggable.js) with webpack. Perhaps he has some information to share as well.
